# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MAVEN_OPTS: --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
      CLOUD_DB_HOST: 127.0.0.1
      CLOUD_DB_USER: root
      CLOUD_DB_PWD: root
      CLOUD_DB_SCHEMA: drscloud
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Start MySQL server
      run: sudo /etc/init.d/mysql start
      
    - name: MySQL Schema creation
      run: mysql --user=root --password=root --execute="CREATE DATABASE drsci;"
      
    - name: Build, Test and generate reports
      run: mvn -T 6 -P ci -B test
      
    - name: Publish reports
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: Tests/Services/target/surefire-reports/testng-*.xml
        reporter: java-junit        # Format of test results
