name: run-tests-withreports

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MAVEN_OPTS: --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
      CLOUD_DB_HOST: 127.0.0.1
      CLOUD_DB_USER: root
      CLOUD_DB_PWD: root
      CLOUD_DB_SCHEMA: drscloud
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
        
      - name: Start MySQL server
        run: sudo /etc/init.d/mysql start

      - name: MySQL Schema creation
        run: mysql --user=root --password=root --execute="CREATE DATABASE drsci;"

      - name: Run Test
        if: always()
        run: mvn -T 6 package -P ci -B test
        continue-on-error: true

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: 2gh_pages2

      - name: Allure Report with history
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          allure_results: Tests/Services/target/allure-results
          gh_pages: 2gh-pages2
          allure_report: 3allure-report3
          allure_history: 4allure-history4

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: /home/runner/work/drs-cloud-ws/drs-cloud-ws/Tests/Services/allure-history
